// Package data 测试数据
package data

import (
	"fmt"
	"time"

	"github.com/xiaochangtongxue/my-gin/internal/model"
)

// UserFixtures 用户测试数据
var UserFixtures = []model.User{
	{
		Username: "testuser1",
		Mobile:   "13800000001",
		Password: "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy", // bcrypt hash of "password123"
	},
	{
		Username: "testuser2",
		Mobile:   "13800000002",
		Password: "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy",
	},
	{
		Username: "lockeduser",
		Mobile:   "13800000003",
		Password: "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy",
	},
}

// GetValidUser 获取有效用户
func GetValidUser() model.User {
	return UserFixtures[0]
}

// GetLockedUser 获取被锁定的用户
func GetLockedUser() model.User {
	return UserFixtures[2]
}

// GenerateTestUser 生成测试用户
func GenerateTestUser(suffix int) model.User {
	timestamp := time.Now().UnixNano() + int64(suffix)
	return model.User{
		Username: fmt.Sprintf("autogenerated_%d", timestamp),
		Mobile:   fmt.Sprintf("139%08d", timestamp%100000000),
		Password: "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy",
	}
}

// APIRequestFixtures API 请求测试数据
type APIRequestFixtures struct{}

// ValidRegisterRequest 有效的注册请求
func (APIRequestFixtures) ValidRegisterRequest() map[string]interface{} {
	return map[string]interface{}{
		"username": "testuser",
		"mobile":   "13800000000",
		"password": "Password123",
	}
}

// InvalidRegisterRequest 无效的注册请求（密码太短）
func (APIRequestFixtures) InvalidRegisterRequest() map[string]interface{} {
	return map[string]interface{}{
		"username": "testuser",
		"mobile":   "13800000000",
		"password": "123",
	}
}

// ValidLoginRequest 有效的登录请求
func (APIRequestFixtures) ValidLoginRequest() map[string]interface{} {
	return map[string]interface{}{
		"mobile":   "13800000001",
		"password": "password123",
	}
}

// InvalidLoginRequest 无效的登录请求
func (APIRequestFixtures) InvalidLoginRequest() map[string]interface{} {
	return map[string]interface{}{
		"mobile":   "13800000001",
		"password": "wrongpassword",
	}
}

// TestData 测试数据集合
type TestData struct {
	Users APIRequestFixtures
}

// Fixtures 测试数据入口
var Fixtures = &TestData{
	Users: APIRequestFixtures{},
}
