system:
  env: dev
  port: 8080
  appname: gin=-app
  appurl: http://localhost

mysql:
  name: "root"
  host: "127.0.0.1"
  port: 3306
  password: 123456
  dbname: "test"
  
redis:
  host: "127.0.0.1"
  port: 6379
