// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/xiaochangtongxue/my-gin/internal/app"
	"github.com/xiaochangtongxue/my-gin/internal/middleware"
	"github.com/xiaochangtongxue/my-gin/internal/modules/auth"
	"github.com/xiaochangtongxue/my-gin/internal/modules/docs"
	"github.com/xiaochangtongxue/my-gin/internal/modules/health"
	"github.com/xiaochangtongxue/my-gin/internal/modules/metrics"
	"github.com/xiaochangtongxue/my-gin/internal/modules/permission"
	"github.com/xiaochangtongxue/my-gin/internal/modules/security"
	"github.com/xiaochangtongxue/my-gin/pkg/cache"
	"github.com/xiaochangtongxue/my-gin/pkg/config"
	"github.com/xiaochangtongxue/my-gin/pkg/database"
	"github.com/xiaochangtongxue/my-gin/pkg/jwt"
	metrics2 "github.com/xiaochangtongxue/my-gin/pkg/metrics"
	"gorm.io/gorm"
)

import (
	_ "github.com/xiaochangtongxue/my-gin/api"
)

// Injectors from wire.go:

// InitializeApp 初始化应用程序（Wire 生成）
//
//go:generate wire
func InitializeApp(configFile2 string) (*app.App, error) {
	config, err := ProvideConfig(configFile2)
	if err != nil {
		return nil, err
	}
	db, err := ProvideDB(config)
	if err != nil {
		return nil, err
	}
	cache, err := ProvideRedisCache(config)
	if err != nil {
		return nil, err
	}
	manager := ProvideJWTManager(config)
	engine := ProvideGinEngine(config, manager, cache)
	module := docs.NewModule()
	healthHandler := health.ProvideHealthHandler(db, cache)
	healthModule := health.NewModule(healthHandler)
	metricsModule := metrics.NewModule()
	refreshTokenRepository := auth.ProvideRefreshTokenRepository(db)
	userRepository := auth.ProvideUserRepository(db)
	securityService := security.ProvideSecurityService(cache, config)
	captcha := auth.ProvideCaptcha(config, cache)
	notifier := auth.ProvideNotifier()
	authService := auth.ProvideAuthService(refreshTokenRepository, cache, manager, config, userRepository, securityService, captcha, notifier)
	authHandler := auth.ProvideAuthHandler(authService)
	captchaHandler := auth.ProvideCaptchaHandler(captcha)
	authModule := auth.NewModule(authHandler, captchaHandler)
	securityHandler := security.ProvideSecurityHandler(securityService)
	permissionChecker, err := permission.ProvidePermissionChecker(config, db)
	if err != nil {
		return nil, err
	}
	userRoleRepository := permission.ProvideUserRoleRepository(db)
	securityModule := security.NewModule(securityHandler, permissionChecker, userRoleRepository)
	roleRepository := permission.ProvideRoleRepository(db)
	permissionService := permission.ProvidePermissionService(db, roleRepository, userRoleRepository, permissionChecker)
	permissionHandler := permission.ProvidePermissionHandler(permissionService)
	permissionModule := permission.NewModule(permissionHandler, permissionChecker, userRoleRepository)
	v := ProvideRouteModules(module, healthModule, metricsModule, authModule, securityModule, permissionModule)
	appApp := app.New(config, db, cache, manager, engine, v)
	return appApp, nil
}

// wire.go:

// ProvideConfig 提供配置
func ProvideConfig(configFile2 string) (*config.Config, error) {
	return config.Init(configFile2)
}

// ProvideDB 提供数据库连接
func ProvideDB(cfg *config.Config) (*gorm.DB, error) {
	if err := database.Init(&cfg.Database); err != nil {
		return nil, err
	}
	return database.Get(), nil
}

// ProvideRedisCache 提供 Redis 缓存
func ProvideRedisCache(cfg *config.Config) (cache.Cache, error) {
	if err := cache.InitRedis(&cfg.Redis); err != nil {
		return nil, err
	}
	return cache.NewRedisCache(), nil
}

// ProvideJWTManager 提供 JWT 管理器
func ProvideJWTManager(cfg *config.Config) *jwt.Manager {
	mgr := jwt.NewManager(jwt.Config{
		Secret:     cfg.JWT.Secret,
		ExpireTime: cfg.JWT.ExpireTime,
		Issuer:     cfg.JWT.Issuer,
	})
	jwt.Init(jwt.Config{
		Secret:     cfg.JWT.Secret,
		ExpireTime: cfg.JWT.ExpireTime,
		Issuer:     cfg.JWT.Issuer,
	})
	return mgr
}

// ProvideGinEngine 提供 Gin 引擎
func ProvideGinEngine(cfg *config.Config, jwtMgr *jwt.Manager, redisCache cache.Cache) *gin.Engine {
	gin.SetMode(cfg.Server.Mode)
	engine := gin.New()
	metrics2.AppStartTime.
		SetToCurrentTime()
	middleware.ApplyWithConfig(engine, cfg, middleware.DefaultMiddleware{
		EnableRecovery:  true,
		EnableRequestID: true,
		EnableLogger:    true,
		EnableCORS:      true,
		EnableSecurity:  true,
		EnableXSS:       false,
		EnableCSRF:      cfg.Middleware.CSRF.Enable,
		EnableAuth:      true,
		EnableMetrics:   cfg.Middleware.Metrics.Enable,
		EnableRateLimit: cfg.Middleware.RateLimit.Enable,
		AuthSkipPaths:   cfg.Middleware.Auth.SkipPaths,
		AuthJWTMgr:      jwtMgr,
		AuthCache:       redisCache,
		RateLimitCache:  redisCache,
	})

	return engine
}

// ProvideRouteModules keeps route registration order explicit.
func ProvideRouteModules(docs2 *docs.Module, health2 *health.Module, metrics3 *metrics.Module, auth2 *auth.Module, security2 *security.Module, permission2 *permission.Module,
) []app.RouteModule {
	return []app.RouteModule{docs2, health2, metrics3, auth2, security2, permission2}
}

var infraSet = wire.NewSet(
	ProvideConfig,
	ProvideDB,
	ProvideRedisCache,
	ProvideJWTManager,
	ProvideGinEngine,
)

var moduleSet = wire.NewSet(docs.ProviderSet, health.ProviderSet, metrics.ProviderSet, permission.ProviderSet, security.ProviderSet, auth.ProviderSet, ProvideRouteModules)
