// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/xiaochangtongxue/my-gin/internal/handler"
	"github.com/xiaochangtongxue/my-gin/internal/middleware"
	"github.com/xiaochangtongxue/my-gin/internal/repository"
	"github.com/xiaochangtongxue/my-gin/internal/service"
	"github.com/xiaochangtongxue/my-gin/pkg/cache"
	"github.com/xiaochangtongxue/my-gin/pkg/config"
	"github.com/xiaochangtongxue/my-gin/pkg/database"
	"github.com/xiaochangtongxue/my-gin/pkg/jwt"
	"gorm.io/gorm"
)

import (
	_ "github.com/xiaochangtongxue/my-gin/docs"
)

// Injectors from wire.go:

// InitializeApp 初始化应用程序（Wire 生成）
//
//go:generate wire
func InitializeApp(configFile2 string) (*App, error) {
	config, err := ProvideConfig(configFile2)
	if err != nil {
		return nil, err
	}
	db, err := ProvideDB(config)
	if err != nil {
		return nil, err
	}
	cache, err := ProvideRedisCache(config)
	if err != nil {
		return nil, err
	}
	manager := ProvideJWTManager(config)
	engine := ProvideGinEngine(config, manager, cache)
	refreshTokenRepository := ProvideRefreshTokenRepository(db)
	authService := ProvideAuthService(refreshTokenRepository, cache, manager, config)
	authHandler := ProvideAuthHandler(authService)
	healthHandler := ProvideHealthHandler(db, cache)
	app := &App{
		Config:        config,
		DB:            db,
		Cache:         cache,
		JWTMgr:        manager,
		Engine:        engine,
		AuthHandler:   authHandler,
		HealthHandler: healthHandler,
	}
	return app, nil
}

// wire.go:

// ProvideConfig 提供配置
func ProvideConfig(configFile2 string) (*config.Config, error) {
	return config.Init(configFile2)
}

// ProvideDB 提供数据库连接
func ProvideDB(cfg *config.Config) (*gorm.DB, error) {
	if err := database.Init(&cfg.Database); err != nil {
		return nil, err
	}
	return database.Get(), nil
}

// ProvideRedisCache 提供 Redis 缓存
func ProvideRedisCache(cfg *config.Config) (cache.Cache, error) {
	if err := cache.InitRedis(&cfg.Redis); err != nil {
		return nil, err
	}
	return cache.NewRedisCache(), nil
}

// ProvideJWTManager 提供 JWT 管理器
func ProvideJWTManager(cfg *config.Config) *jwt.Manager {
	mgr := jwt.NewManager(jwt.Config{
		Secret:     cfg.JWT.Secret,
		ExpireTime: cfg.JWT.ExpireTime,
		Issuer:     cfg.JWT.Issuer,
	})
	jwt.Init(jwt.Config{
		Secret:     cfg.JWT.Secret,
		ExpireTime: cfg.JWT.ExpireTime,
		Issuer:     cfg.JWT.Issuer,
	})
	return mgr
}

// ProvideRefreshTokenRepository 提供 Refresh Token 仓储
func ProvideRefreshTokenRepository(db *gorm.DB) repository.RefreshTokenRepository {
	return repository.NewRefreshTokenRepository(db)
}

// ProvideAuthService 提供认证服务
func ProvideAuthService(
	rtRepo repository.RefreshTokenRepository,
	redisCache cache.Cache,
	jwtMgr *jwt.Manager,
	cfg *config.Config,
) *service.AuthService {
	return service.NewAuthService(rtRepo, redisCache, jwtMgr, service.Config{
		AccessTokenExpire:  cfg.JWT.ExpireTime,
		RefreshTokenExpire: cfg.JWT.RefreshExpireTime,
	})
}

// ProvideAuthHandler 提供认证处理器
func ProvideAuthHandler(authSvc *service.AuthService) *handler.AuthHandler {
	return handler.NewAuthHandler(authSvc)
}

// ProvideHealthHandler 提供健康检查处理器
func ProvideHealthHandler(db *gorm.DB, cache2 cache.Cache) *handler.HealthHandler {
	return handler.NewHealthHandler(db, cache2)
}

// ProvideGinEngine 提供 Gin 引擎
func ProvideGinEngine(cfg *config.Config, jwtMgr *jwt.Manager, redisCache cache.Cache) *gin.Engine {
	gin.SetMode(cfg.Server.Mode)
	engine := gin.New()
	middleware.ApplyWithConfig(engine, cfg, middleware.DefaultMiddleware{
		EnableRecovery:  true,
		EnableRequestID: true,
		EnableLogger:    true,
		EnableCORS:      true,
		EnableSecurity:  true,
		EnableXSS:       false,
		EnableCSRF:      cfg.Middleware.CSRF.Enable,
		EnableAuth:      true,
		EnableMetrics:   cfg.Middleware.Metrics.Enable,
		AuthSkipPaths:   cfg.Middleware.Auth.SkipPaths,
		AuthJWTMgr:      jwtMgr,
		AuthCache:       redisCache,
	})

	return engine
}

// infraSet 基础设施 ProviderSet
var infraSet = wire.NewSet(
	ProvideConfig,
	ProvideDB,
	ProvideRedisCache,
	ProvideJWTManager,
)

// repoSet Repository ProviderSet
var repoSet = wire.NewSet(
	ProvideRefreshTokenRepository,
)

// serviceSet Service ProviderSet
var serviceSet = wire.NewSet(
	ProvideAuthService,
)

// handlerSet Handler ProviderSet
var handlerSet = wire.NewSet(
	ProvideAuthHandler,
	ProvideHealthHandler,
)

// engineSet Gin Engine ProviderSet
var engineSet = wire.NewSet(
	ProvideGinEngine,
)

// App 应用程序依赖容器
type App struct {
	Config        *config.Config
	DB            *gorm.DB
	Cache         cache.Cache
	JWTMgr        *jwt.Manager
	Engine        *gin.Engine
	AuthHandler   *handler.AuthHandler
	HealthHandler *handler.HealthHandler
}
